// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class NewArmoury
    {
        public static class Keyword
        {
            private static FormLink<IKeywordGetter> Construct(uint id) => new(ModKey.MakeFormKey(id));
            public static FormLink<IKeywordGetter> WeapTypeRapier => Construct(0x801);
            public static FormLink<IKeywordGetter> WeapTypePike => Construct(0xe457e);
            public static FormLink<IKeywordGetter> WeapTypeSpear => Construct(0xe457f);
            public static FormLink<IKeywordGetter> WeapTypeHalberd => Construct(0xe4580);
            public static FormLink<IKeywordGetter> WeapTypeQtrStaff => Construct(0xe4581);
            public static FormLink<IKeywordGetter> WeapTypeCestus => Construct(0x19aab3);
            public static FormLink<IKeywordGetter> WeapTypeClaw => Construct(0x19aab4);
            public static FormLink<IKeywordGetter> NA_CantParry => Construct(0x19aab5);
            public static FormLink<IKeywordGetter> NA_InflictBleed => Construct(0x1aef07);
            public static FormLink<IKeywordGetter> NAR_Sig => Construct(0x20509e);
            public static FormLink<IKeywordGetter> AltDagger => Construct(0x2b65bb);
            public static FormLink<IKeywordGetter> AltMace => Construct(0x2b65bc);
            public static FormLink<IKeywordGetter> WeapTypeWhip => Construct(0x31bd77);
            public static FormLink<IKeywordGetter> NA_UniIWhp => Construct(0x31bd78);
            public static FormLink<IKeywordGetter> NA_UniEWhp => Construct(0x31bd79);
            public static FormLink<IKeywordGetter> NA_UniFWhp => Construct(0x31bd7a);
        }
    }
}
