// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class NewArmoury
    {
        public readonly static ModKey ModKey = ModKey.FromNameAndExtension("NewArmoury.esp");
    }
}
