// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class WayOfTheMonk
    {
        public static class Keyword
        {
            private static FormLink<IKeywordGetter> Construct(uint id) => new (ModKey.MakeFormKey(id));
            public static FormLink<IKeywordGetter> WeapTypeUnarmed => Construct(0xd6d);
            public static FormLink<IKeywordGetter> WoMHandArmorWeapon => Construct(0x2dfa);
            public static FormLink<IKeywordGetter> WoMHandWeapon => Construct(0x2dfc);
            public static FormLink<IKeywordGetter> WOM_Med_Benefit => Construct(0x222468);
        }
    }
}
