// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    /// <summary>
    ///	Adds support for keywords from the Way Of The Monk mod.
    ///	Currently maintained nexus page as of 21-09-04: https://www.nexusmods.com/skyrimspecialedition/mods/17684
    /// </summary>
    public static partial class WayOfTheMonk
    {
        public readonly static ModKey ModKey = ModKey.FromNameAndExtension("WayOfTheMonk.esp");
    }
}
