// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Plugins;
using Mutagen.Bethesda.Skyrim;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class NWTA
    {
        public static class Keyword
        {
            private static FormLink<IKeywordGetter> Construct(uint id) => new (ModKey.MakeFormKey(id));
            public static FormLink<IKeywordGetter> WeapTypeKatana => Construct(0xd61);
            public static FormLink<IKeywordGetter> WeapTypeCurvedSword => Construct(0xd71);
        }
    }
}
