// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    public static partial class NWTA
    {
        public readonly static ModKey ModKey = ModKey.FromNameAndExtension("NWTA.esp");
    }
}
