// Autogenerated by https://github.com/Mutagen-Modding/Mutagen.Bethesda.FormKeys

using Mutagen.Bethesda.Plugins;

namespace Mutagen.Bethesda.FormKeys.SkyrimSE
{
    /// <summary>
    ///	Adds support for keywords from the New Weapon Types and Animation Support mod.
    ///	Currently maintained nexus page as of 21-09-04: https://www.nexusmods.com/skyrimspecialedition/mods/33985
    /// </summary>
    public static partial class NWTA
    {
        public readonly static ModKey ModKey = ModKey.FromNameAndExtension("NWTA.esp");
    }
}
